package com.whs.entity;

import java.util.Date;

public class BAbc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_abc.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_abc.age
     *
     * @mbggenerated
     */
    private Date age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_abc.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_abc.lastUpdateTime
     *
     * @mbggenerated
     */
    private Date lastupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_abc.createUser
     *
     * @mbggenerated
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_abc.lastUpdateUser
     *
     * @mbggenerated
     */
    private String lastupdateuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_abc.id
     *
     * @return the value of b_abc.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_abc.id
     *
     * @param id the value for b_abc.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_abc.age
     *
     * @return the value of b_abc.age
     *
     * @mbggenerated
     */
    public Date getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_abc.age
     *
     * @param age the value for b_abc.age
     *
     * @mbggenerated
     */
    public void setAge(Date age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_abc.createTime
     *
     * @return the value of b_abc.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_abc.createTime
     *
     * @param createtime the value for b_abc.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_abc.lastUpdateTime
     *
     * @return the value of b_abc.lastUpdateTime
     *
     * @mbggenerated
     */
    public Date getLastupdatetime() {
        return lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_abc.lastUpdateTime
     *
     * @param lastupdatetime the value for b_abc.lastUpdateTime
     *
     * @mbggenerated
     */
    public void setLastupdatetime(Date lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_abc.createUser
     *
     * @return the value of b_abc.createUser
     *
     * @mbggenerated
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_abc.createUser
     *
     * @param createuser the value for b_abc.createUser
     *
     * @mbggenerated
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_abc.lastUpdateUser
     *
     * @return the value of b_abc.lastUpdateUser
     *
     * @mbggenerated
     */
    public String getLastupdateuser() {
        return lastupdateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_abc.lastUpdateUser
     *
     * @param lastupdateuser the value for b_abc.lastUpdateUser
     *
     * @mbggenerated
     */
    public void setLastupdateuser(String lastupdateuser) {
        this.lastupdateuser = lastupdateuser == null ? null : lastupdateuser.trim();
    }
}