package com.whs.mapper;

import com.whs.entity.BAbc;
import com.whs.entity.BAbcExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BAbcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_abc
     *
     * @mbggenerated
     */
    int countByExample(BAbcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_abc
     *
     * @mbggenerated
     */
    int deleteByExample(BAbcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_abc
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_abc
     *
     * @mbggenerated
     */
    int insert(BAbc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_abc
     *
     * @mbggenerated
     */
    int insertSelective(BAbc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_abc
     *
     * @mbggenerated
     */
    List<BAbc> selectByExample(BAbcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_abc
     *
     * @mbggenerated
     */
    BAbc selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_abc
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BAbc record, @Param("example") BAbcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_abc
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BAbc record, @Param("example") BAbcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_abc
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BAbc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_abc
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BAbc record);
}